Feature/issue 3 implement blog features
Tam9927/Bloggist pull request #5
Opened 2023-03-21 03:47 UTC by Tam9927

2023-03-25 14:02 UTC, rafaelragib requested changes

2023-03-25 14:02 UTC, rafaelragib commented on Backend/Model/blog.model.js
> +      defaultValue: DataTypes.UUIDV4,
i don't think this should have a default value

2023-03-26 16:20 UTC, Tam9927 commented on Backend/Controller/blog.controller.js
> +    const blog = await BlogService.getBlogByBlogId(req.params.blogId);
The primitive datatype here is auto generated UUID  which is a string itself.

2023-03-28 04:38 UTC, rafaelragib commented
There are some reviews that hasn't been resolved. Fix them and fix the conflict

2023-03-28 07:01 UTC, merged